; esp32/platformio.ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Baixa as bibliotecas de WebServer e WebSocket sozinhas
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    mathieucarbou/AsyncTCP @ ^3.2.14

; Configuração para conseguir fazer o upload da pasta /data (onde está o index.html) para a memória flash
board_build.filesystem = littlefs
